name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    steps:
      - name: 23f2001992@ds.study.iitm.ac.in
        run: echo "Hello, world!"
